### PR TITLE
Add Mandelbrot shader

### PR DESCRIPTION
**Pull request by kant2002**
It does not perform that well on full screen, but I think that's much interesting sample with rich cultural background

image

### CODE REVIEW

**Comment by rickbrew** [comment]
Here's Paint.NET 5.0's Mandelbrot Fractal shader code -- it has some fun properties to experiment with. Feel free to port it over here to ComputeSharp. https://gist.github.com/rickbrew/479e5e3e7b1d8ba7b4e76fc1246bb229

image

**Comment by kant2002** [comment]
Obviously much better looking then  mine. But at least I was able to better understand API by implementing things myself. What if I just borrow colors generation function? I think simpler version better for educational purposes. I hope Mandelbrot still popular enough to be easiest recognizable

**Comment by rickbrew** [comment]
> What if I just borrow colors generation function?
Borrow whatever you want :)

**Comment by Sergio0694** [comment]
Closing this for now. The fact it can't run in realtime also makes it not really ideal for the sample app. We might reconsider porting the version from Paint.NET in the future perhaps as a unit test and sample for people to check out, I suppose. Thank you! 🙂

**Pull request closed without merging**
