### PR TITLE
Add atmospheric scattering example

### LINKED ISSUE #484: Add atmospheric scattering example
### Description

Atmospheric scattering demonstration similar to [NASA rotating Earth](https://svs.gsfc.nasa.gov/30082)

This example will be made by simple generic scattering with mie and rayleigh phases and also using day and night textures.

### PR DESCRIPTION
**Pull request by malstraem**
### Description

This PR provide implementation of atmosphere scattering example

### CODE REVIEW

**Comment by Malstraem** [comment]
@Sergio0694,
>Эй, спасибо за ваш интерес! 🙂

Thanks for your remarks 😃 

>Did you write your shader or was it ported? If so, what is the license?

Shader is mostly based on [this](https://www.shadertoy.com/view/lslXDr) and i think at the end of the work it will be the same. It's have default shadertoy license and there are no problems here, as with other samples.

>What is the license for those textures, where are they from?

Textures taken from [here](https://www.solarsystemscope.com/textures/) - under Attribution 4.0 are no problems.

Of course i will provide all appropriate credits before PR finished (but what form for textures? in code at using line or csproj at resource line?).

**Comment by malstraem** [comment]
@Sergio0694 hi, I finally have free time and I continue to work on PR and I have a question:

winui window code behind contains 

```csharp
foreach ((AnimatedComputeShaderPanel panel, object _) in this.shaderPanels)
{
    panel.ShaderRunner = null;
}
```
and its have possible null reference assignment (CS8601) that warns by default and its should be `object?`. And your build treats warnings as errors and im not able to build winui sample. What am i missing, how CI built it?

**Comment by Sergio0694** [comment]
Yup I noticed the same in another unrelated PR, will fix that 🙂

By the way, not sure what you did but this branch got pretty messed up, look at the commit history and changes 😅
You should isolate the actual commits with your changes and rebase with just those on top of main, then force push.

**Comment by malstraem** [comment]
@Sergio0694, i did rebase and yeah it's looks strange :clown_face:. Maybe previous merge affect this. I think it's right to clear the whole history and start from scratch.

**Pull request closed without merging**
