### PR TITLE
Hlsl.Distance output to scalar float

### PR DESCRIPTION
**Pull request by Patan77**
Hlsl.Distance had incorrect output type should be float

### CODE REVIEW

**Comment by Sergio0694** [comment]
Whoops, thank you for spotting the mistake! 😄

The fix is not correct though: you changed a file that is autogenerated.
ComputeSharp is using what is called "T4 templates" (those `.tt` and `.ttinclude` files) to generate all these `.g.cs` files you see. In case you're not familiar with them, you can learn more in the docs [here](https://docs.microsoft.com/en-us/visualstudio/modeling/code-generation-and-t4-text-templates). In a nutshell, a T4 template is simply a C# file that is executed by the templating engine when you trigger it, and it will generate a file you can then include in your project automatically. It's very handy in cases where you have tons of code that can be procedurally generated 🙂

In order to fix this, you'll need to fix the actual template. The issue is here, in the return type:

https://github.com/Sergio0694/ComputeSharp/blob/44c3cb9410dd3b388e4918d646f6a4238b79ac53/src/ComputeSharp/Core/Intrinsics/Hlsl.ttinclude#L823-L828

Once you fix it, click on Build > Transform All T4 Templates (from the Visual Studio toolbar at the top). That will re-run all T4 templates and update the generated files. Once you do that, please also squash that commit with this first one, so we'll only end up with one containing the fix. Let me know if you need help to do the rebase in case you're not familiar with it! 👍

**Comment by Patan77** [comment]
Ok thanks, didn't know that.  :thumbsup:

**Comment by Sergio0694** [comment]
Do you need help doing the rebase? I can do that for you if you want, too.
This PR should be a single commit, with your two squashed together, no merge commit, and rebased on top of `main`.

**Comment by Patan77** [comment]
Sure if you can, I'm new to working with git / github don't really know what I am doing, still trying to figure things out. :dizzy_face:

**Comment by Sergio0694** [comment]
No problem! In case it helps, here's a guide on interactive rebases: https://www.sitepoint.com/git-interactive-rebase-guide/.
The general idea here was to fix two issues:

- The first commit was incorrect, so we don't want it in the history. We just want the second one with the changes.
- The merge is an unnecessary commit. If you want a branch to be back on sync with `main`, instead of merging `main` into your branch you can just rebase yoru branch _on top_ of `main`. That is, you pick the commits from your branch, then basically reapply them on top of what `main` is right now, then force push to your branch to overwrite its state with the changes.

In this case, I just had to do:

> `git rebase -i HEAD~2`

This starts an interactive rebase, and `HEAD~2` tells git "we only need to thinker with the last two commits".
This will open a text editor of your choice with these two lines, one per commit:

```
pick 8bb11cd Hlsl Distance ttinclude return to float
pick 44c3cb9 Change Hlsl Distance to return float
```

We don't need the old commit, so we just change that `pick` to `drop` in that line, then save and close.
Now we just need to force push to overwrite the remote branch. In your case, this would be:

> `git status`

Just to double check what branch you're on. In this case it was just `main` for you.
Then you just run:

> `git push --force origin main`

Where `main` is the target branch name. This will push to that branch and overwrite the history.

And that's it, now we have a clean branch with just that commit we need, and no extra clutter 😄

**Review by Sergio0694 — APPROVED** [review]
:shipit:

**Pull request merged**
